# Generated by Django 6.0.3 on 2026-03-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.FileField(upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SesionFotos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoSeleccionada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lente.foto')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lente.seleccioncliente')),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lente.sesionfotos'),
        ),
        migrations.AddField(
            model_name='sesionfotos',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lente.usuario'),
        ),
        migrations.AddField(
            model_name='seleccioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lente.usuario'),
        ),
    ]
