# Generated by Django 6.0.3 on 2026-03-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lente', '0002_alter_foto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccioncliente',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado correctamente'), ('CANCELADO', 'Cancelado por cliente')], default='PENDIENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='seleccioncliente',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seleccioncliente',
            name='notas_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
